name: 'Polaris Code Scanner'
description: "SAST Polaris Scan action for 64 bit Linux runners"
inputs:
  POLARIS_SERVER_URL:
    description: "Polaris server URL"
    required: true
  POLARIS_ACCESS_TOKEN:
    description: "Polaris server access token"
    required: true
  POLARIS_COMMAND_OPTS:
    required: false
    description: "Polaris command line options"
    default: " "
  POLARIS_PROJECT_NAME:
    required: true
    description: "Polaris Project for scan results"
  POLARIS_PROJECT_BRANCH:
    required: true
    description: "Polaris project branch for scan results"
runs:
  using: "composite"
  steps:
    - name: Downloading SAST Polaris CLI
      run: wget -q ${{ inputs.polaris_server_url }}/api/tools/polaris_cli-linux64.zip
      shell: bash
    - name: Extracting polaris_cli-linux64.zip to tmp
      run: unzip -j polaris_cli-linux64.zip -d /tmp
      shell: bash
    - name: Running Scan
      run: |
        export POLARIS_ACCESS_TOKEN=${{ inputs.polaris_access_token }}
        export POLARIS_SERVER_URL=${{ inputs.polaris_server_url }}
        export POLARIS_REPO_NAME=${{ inputs.polaris_project_name }}
        export GIT_BRANCH=${{inputs.polaris_project_branch}}
        /tmp/polaris ${{ inputs.polaris_command_opts }} --co project.name=\"${{ inputs.polaris_project_name }}\" analyze -w 
        cat .synopsys/polaris/cli-scan.json
      shell: bash
